import sys
import json
import os

from parser import parse_netlist


# =========================================================
# PS13 STATIC TIMING ANALYSIS
# =========================================================
#
# This module performs an estimated gate-level static timing
# analysis using predefined gate delays.
#
# It works with the gate structure used by parser.py:
#
# {
#     "name":   gate instance name,
#     "type":   gate type,
#     "inputs": [input signals],
#     "output": output signal
# }
#
# =========================================================


# ---------------------------------------------------------
# Default gate delays
# ---------------------------------------------------------
#
# These are demonstration/model delays.
# They are NOT technology-library timing values.
#
# Units: nanoseconds
# ---------------------------------------------------------

GATE_DELAYS = {
    "and": 1.5,
    "or": 1.5,
    "not": 1.0,
    "nand": 1.3,
    "nor": 1.3,
    "xor": 2.0,
    "xnor": 2.0,
    "buf": 1.0,
}


# ---------------------------------------------------------
# Normalize gate type
# ---------------------------------------------------------

def normalize_gate_type(gate_type):
    """
    Convert gate type to lowercase and remove whitespace.
    """

    return str(gate_type).strip().lower()


# ---------------------------------------------------------
# Get gate delay
# ---------------------------------------------------------

def get_gate_delay(gate_type):
    """
    Return estimated delay for a gate.
    """

    gate_type = normalize_gate_type(gate_type)

    if gate_type not in GATE_DELAYS:
        raise ValueError(
            f"Unsupported gate type for timing analysis: {gate_type}"
        )

    return GATE_DELAYS[gate_type]


# ---------------------------------------------------------
# Build circuit information
# ---------------------------------------------------------

def build_timing_graph(gates):
    """
    Build timing-related lookup tables.
    """

    creators = {}
    downstream = {}

    for gate in gates:

        output = gate["output"]

        creators[output] = gate

        for signal in gate["inputs"]:

            if signal not in downstream:
                downstream[signal] = []

            downstream[signal].append(gate)

    return creators, downstream


# ---------------------------------------------------------
# Find primary inputs
# ---------------------------------------------------------

def find_primary_inputs(gates, creators):
    """
    A signal is treated as a primary input when it appears
    as a gate input but is not generated by another gate.
    """

    primary_inputs = set()

    for gate in gates:

        for signal in gate["inputs"]:

            if signal not in creators:
                primary_inputs.add(signal)

    return sorted(primary_inputs)


# ---------------------------------------------------------
# Find circuit outputs
# ---------------------------------------------------------

def find_circuit_outputs(gates, creators):
    """
    A signal is considered a circuit output when it is created
    by a gate but is never used as an input to another gate.
    """

    generated_signals = set(creators.keys())

    used_signals = set()

    for gate in gates:

        for signal in gate["inputs"]:
            used_signals.add(signal)

    outputs = generated_signals - used_signals

    return sorted(outputs)


# ---------------------------------------------------------
# Topological ordering
# ---------------------------------------------------------

def topological_sort(gates):
    """
    Return gates in dependency order.

    This makes the timing calculation independent of the
    order in which gates happen to appear in the Verilog file.
    """

    creators = {}

    for gate in gates:
        creators[gate["output"]] = gate

    remaining = list(gates)
    ordered = []

    resolved_signals = set()

    # Primary inputs are considered available immediately.
    for gate in gates:

        for signal in gate["inputs"]:

            if signal not in creators:
                resolved_signals.add(signal)

    while remaining:

        progress = False

        for gate in remaining[:]:

            inputs_ready = True

            for signal in gate["inputs"]:

                if signal not in resolved_signals:
                    inputs_ready = False
                    break

            if inputs_ready:

                ordered.append(gate)

                resolved_signals.add(
                    gate["output"]
                )

                remaining.remove(gate)

                progress = True

        if not progress:

            unresolved = [
                gate["name"]
                for gate in remaining
            ]

            raise ValueError(
                "Unable to determine gate dependency order. "
                f"Possible circular or unresolved logic involving: "
                f"{unresolved}"
            )

    return ordered


# ---------------------------------------------------------
# Calculate arrival times
# ---------------------------------------------------------

def calculate_arrival_times(gates):
    """
    Calculate signal arrival time using:

        output arrival =
        maximum(input arrival) + gate delay

    Primary inputs have arrival time 0 ns.
    """

    ordered_gates = topological_sort(gates)

    arrival_times = {}

    gate_timing = {}

    # Primary inputs arrive at time zero.
    for gate in gates:

        for signal in gate["inputs"]:

            if signal not in arrival_times:
                arrival_times[signal] = 0.0

    for gate in ordered_gates:

        name = gate["name"]
        gate_type = normalize_gate_type(
            gate["type"]
        )

        inputs = gate["inputs"]
        output = gate["output"]

        delay = get_gate_delay(
            gate_type
        )

        input_arrivals = []

        for signal in inputs:

            if signal not in arrival_times:
                arrival_times[signal] = 0.0

            input_arrivals.append(
                arrival_times[signal]
            )

        if input_arrivals:

            latest_input_time = max(
                input_arrivals
            )

        else:

            latest_input_time = 0.0

        output_arrival = (
            latest_input_time + delay
        )

        arrival_times[output] = output_arrival

        gate_timing[name] = {
            "gate": name,
            "type": gate_type,
            "inputs": list(inputs),
            "output": output,
            "delay_ns": delay,
            "latest_input_arrival_ns":
                latest_input_time,
            "output_arrival_ns":
                output_arrival
        }

    return arrival_times, gate_timing


# ---------------------------------------------------------
# Find critical path
# ---------------------------------------------------------

def find_critical_path(gates, arrival_times):
    """
    Backtrace from the circuit output with the largest
    arrival time.

    Returns the longest estimated combinational path.
    """

    creators, _ = build_timing_graph(gates)

    outputs = find_circuit_outputs(
        gates,
        creators
    )

    if not outputs:

        return {
            "delay_ns": 0.0,
            "output": None,
            "path": []
        }

    # Find output with maximum arrival time.
    critical_output = max(
        outputs,
        key=lambda signal:
            arrival_times.get(signal, 0.0)
    )

    critical_delay = arrival_times.get(
        critical_output,
        0.0
    )

    # -----------------------------------------------------
    # Backtrace the path
    # -----------------------------------------------------

    path = []

    current_signal = critical_output

    while current_signal in creators:

        gate = creators[current_signal]

        path.insert(
            0,
            {
                "gate": gate["name"],
                "type": normalize_gate_type(
                    gate["type"]
                ),
                "output": gate["output"]
            }
        )

        # Find the input with the latest arrival.
        inputs = gate["inputs"]

        if not inputs:
            break

        current_signal = max(
            inputs,
            key=lambda signal:
                arrival_times.get(signal, 0.0)
        )

    return {
        "delay_ns": critical_delay,
        "output": critical_output,
        "path": path
    }


# ---------------------------------------------------------
# Analyze all output timing
# ---------------------------------------------------------

def analyze_outputs(gates, arrival_times):
    """
    Return timing information for every circuit output.
    """

    creators, _ = build_timing_graph(gates)

    outputs = find_circuit_outputs(
        gates,
        creators
    )

    result = []

    for output in outputs:

        result.append(
            {
                "signal": output,
                "arrival_time_ns":
                    arrival_times.get(
                        output,
                        0.0
                    )
            }
        )

    result.sort(
        key=lambda item:
            item["arrival_time_ns"],
        reverse=True
    )

    return result


# ---------------------------------------------------------
# Full circuit timing analysis
# ---------------------------------------------------------

def analyze_timing(gates):
    """
    Perform complete static timing analysis.
    """

    if not gates:

        return {
            "gate_count": 0,
            "primary_inputs": [],
            "circuit_outputs": [],
            "arrival_times": {},
            "gate_timing": {},
            "critical_path": {
                "delay_ns": 0.0,
                "output": None,
                "path": []
            }
        }

    creators, downstream = build_timing_graph(
        gates
    )

    primary_inputs = find_primary_inputs(
        gates,
        creators
    )

    outputs = find_circuit_outputs(
        gates,
        creators
    )

    arrival_times, gate_timing = (
        calculate_arrival_times(gates)
    )

    critical_path = find_critical_path(
        gates,
        arrival_times
    )

    output_timing = analyze_outputs(
        gates,
        arrival_times
    )

    return {
        "gate_count": len(gates),

        "primary_inputs":
            primary_inputs,

        "circuit_outputs":
            outputs,

        "arrival_times":
            arrival_times,

        "gate_timing":
            gate_timing,

        "output_timing":
            output_timing,

        "critical_path":
            critical_path
    }


# ---------------------------------------------------------
# Compare clean and Trojan timing
# ---------------------------------------------------------

def compare_timing(clean_result, trojan_result):
    """
    Compare clean and Trojan circuit timing.

    The difference in critical-path delay is used as a
    timing-leakage indicator.
    """

    clean_delay = (
        clean_result[
            "critical_path"
        ][
            "delay_ns"
        ]
    )

    trojan_delay = (
        trojan_result[
            "critical_path"
        ][
            "delay_ns"
        ]
    )

    difference = (
        trojan_delay - clean_delay
    )

    absolute_difference = abs(
        difference
    )

    # -----------------------------------------------------
    # Timing leakage threshold
    # -----------------------------------------------------
    #
    # This is a project-level screening threshold,
    # not a physical measurement limit.
    # -----------------------------------------------------

    leakage_threshold = 0.10

    leakage_detected = (
        absolute_difference
        >= leakage_threshold
    )

    if difference > 0:

        timing_effect = "SLOWER"

    elif difference < 0:

        timing_effect = "FASTER"

    else:

        timing_effect = "NO CHANGE"

    return {
        "clean_critical_path_ns":
            clean_delay,

        "trojan_critical_path_ns":
            trojan_delay,

        "delay_difference_ns":
            difference,

        "absolute_delay_difference_ns":
            absolute_difference,

        "leakage_threshold_ns":
            leakage_threshold,

        "timing_effect":
            timing_effect,

        "leakage_detected":
            leakage_detected
    }


# ---------------------------------------------------------
# Print timing report
# ---------------------------------------------------------

def print_timing_report(result, title="STATIC TIMING ANALYSIS"):
    """
    Print human-readable timing information.
    """

    print("\n")
    print("=" * 70)
    print(
        f"              {title}"
    )
    print("=" * 70)

    print(
        f"\nGates analyzed       : "
        f"{result['gate_count']}"
    )

    print(
        f"Primary inputs       : "
        f"{len(result['primary_inputs'])}"
    )

    print(
        f"Circuit outputs      : "
        f"{len(result['circuit_outputs'])}"
    )

    print("\nCritical Path")
    print("-" * 70)

    critical = result[
        "critical_path"
    ]

    print(
        f"Critical delay       : "
        f"{critical['delay_ns']:.3f} ns"
    )

    print(
        f"Critical output      : "
        f"{critical['output']}"
    )

    if critical["path"]:

        print("\nPath:")

        for index, gate in enumerate(
            critical["path"],
            start=1
        ):

            print(
                f"  {index}. "
                f"{gate['gate']} "
                f"({gate['type']}) "
                f"-> {gate['output']}"
            )

    print("\nOutput Timing")
    print("-" * 70)

    if result["output_timing"]:

        for item in result[
            "output_timing"
        ]:

            print(
                f"  {item['signal']:<20}"
                f"{item['arrival_time_ns']:.3f} ns"
            )

    else:

        print("  No circuit outputs found.")

    print("\nGate Timing")
    print("-" * 70)

    for name, timing in result[
        "gate_timing"
    ].items():

        print(
            f"  {name:<15}"
            f"{timing['type']:<8}"
            f"delay={timing['delay_ns']:.3f} ns  "
            f"arrival={timing['output_arrival_ns']:.3f} ns"
        )

    print("\n" + "=" * 70)


# ---------------------------------------------------------
# Print timing leakage comparison
# ---------------------------------------------------------

def print_timing_comparison(comparison):
    """
    Print clean vs Trojan timing comparison.
    """

    print("\n")
    print("=" * 70)
    print(
        "             TIMING LEAKAGE ANALYSIS"
    )
    print("=" * 70)

    print(
        f"\nClean critical path   : "
        f"{comparison['clean_critical_path_ns']:.3f} ns"
    )

    print(
        f"Trojan critical path  : "
        f"{comparison['trojan_critical_path_ns']:.3f} ns"
    )

    print(
        f"Delay difference      : "
        f"{comparison['delay_difference_ns']:+.3f} ns"
    )

    print(
        f"Absolute difference   : "
        f"{comparison['absolute_delay_difference_ns']:.3f} ns"
    )

    print(
        f"Threshold             : "
        f"{comparison['leakage_threshold_ns']:.3f} ns"
    )

    print(
        f"Timing effect         : "
        f"{comparison['timing_effect']}"
    )

    if comparison[
        "leakage_detected"
    ]:

        print(
            "\n⚠️ TIMING LEAKAGE DETECTED"
        )

        print(
            "The Trojan circuit exhibits "
            "a measurable modeled timing difference."
        )

    else:

        print(
            "\n✅ NO SIGNIFICANT TIMING LEAKAGE"
        )

    print("\n" + "=" * 70)


# ---------------------------------------------------------
# Save JSON report
# ---------------------------------------------------------

def save_timing_report(
    filename,
    timing_result,
    comparison=None
):
    """
    Save timing analysis as JSON.
    """

    report = {
        "analysis": "PS13 Static Timing Analysis",

        "gate_delays_ns":
            GATE_DELAYS,

        "timing_analysis":
            timing_result
    }

    if comparison is not None:

        report[
            "timing_leakage"
        ] = comparison

    directory = os.path.dirname(
        filename
    )

    if directory:

        os.makedirs(
            directory,
            exist_ok=True
        )

    with open(
        filename,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            report,
            file,
            indent=4
        )

    print(
        f"\nTiming report saved to: "
        f"{os.path.abspath(filename)}"
    )


# ---------------------------------------------------------
# Analyze one Verilog file
# ---------------------------------------------------------

def analyze_file(filename):
    """
    Parse and analyze one Verilog netlist.
    """

    print(
        f"\nReading circuit: {filename}"
    )

    gates = parse_netlist(
        filename
    )

    if not gates:

        raise ValueError(
            f"No gates found in {filename}"
        )

    print(
        f"Found {len(gates)} gates."
    )

    result = analyze_timing(
        gates
    )

    return result


# ---------------------------------------------------------
# Main
# ---------------------------------------------------------

def main():

    # -----------------------------------------------------
    # Usage:
    #
    # From project root:
    #
    # python src/timing.py examples/clean.v
    #
    # OR compare clean and Trojan:
    #
    # python src/timing.py \
    #     examples/clean.v \
    #     examples/trojan.v
    # -----------------------------------------------------

    if len(sys.argv) not in (2, 3):

        print(
            "\nUsage:"
        )

        print(
            "  python src/timing.py "
            "examples/clean.v"
        )

        print(
            "\nFor clean vs Trojan comparison:"
        )

        print(
            "  python src/timing.py "
            "examples/clean.v "
            "examples/trojan.v"
        )

        sys.exit(1)

    clean_file = sys.argv[1]

    # -----------------------------------------------------
    # Clean circuit
    # -----------------------------------------------------

    try:

        clean_result = analyze_file(
            clean_file
        )

        print_timing_report(
            clean_result,
            "CLEAN CIRCUIT STATIC TIMING ANALYSIS"
        )

    except Exception as error:

        print(
            "\nERROR analyzing circuit:"
        )

        print(error)

        sys.exit(1)

    # -----------------------------------------------------
    # Save clean report
    # -----------------------------------------------------

    save_timing_report(
        "reports/clean_timing_report.json",
        clean_result
    )

    # -----------------------------------------------------
    # Optional Trojan comparison
    # -----------------------------------------------------

    if len(sys.argv) == 3:

        trojan_file = sys.argv[2]

        try:

            trojan_result = analyze_file(
                trojan_file
            )

            print_timing_report(
                trojan_result,
                "TROJAN CIRCUIT STATIC TIMING ANALYSIS"
            )

        except Exception as error:

            print(
                "\nERROR analyzing Trojan circuit:"
            )

            print(error)

            sys.exit(1)

        # -------------------------------------------------
        # Compare timing
        # -------------------------------------------------

        comparison = compare_timing(
            clean_result,
            trojan_result
        )

        print_timing_comparison(
            comparison
        )

        # -------------------------------------------------
        # Save combined report
        # -------------------------------------------------

        combined_report = {
            "analysis":
                "PS13 Static Timing and "
                "Side-Channel Leakage Analysis",

            "gate_delays_ns":
                GATE_DELAYS,

            "clean_circuit":
                clean_result,

            "trojan_circuit":
                trojan_result,

            "timing_leakage":
                comparison
        }

        os.makedirs(
            "reports",
            exist_ok=True
        )

        with open(
            "reports/timing_leakage_report.json",
            "w",
            encoding="utf-8"
        ) as file:

            json.dump(
                combined_report,
                file,
                indent=4
            )

        print(
            "\nCombined timing report saved to: "
            "reports/timing_leakage_report.json"
        )


# ---------------------------------------------------------
# Program entry point
# ---------------------------------------------------------

if __name__ == "__main__":
    main()